Delete device registration should not use the general-purpose endpoint
 - because it requires 'push-admin' permission and it will fail for 'push-subscribe' only key

Error: 401 "action not permitted"