Make Carthage build script work on Apple Silicon
When running make carthage_package with Xcode 13.4.1, Carthage 0.38.0 on
an Apple Silicon Mac (having first run make update_carthage_dependencies
as described in CONTRIBUTING.md), I was getting the following error:

> Building and archiving…
> # https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file
> # From `carthage help build` we are told that `--archive` implies `--no-skip-current`.
> ./Scripts/carthage-with-workaround-for-issue-3019.sh build --archive --no-use-binaries
> *** xcodebuild output can be found in /var/folders/q2/88t_3skx1rn0gn9znm57tc3c0000gn/T/carthage-xcodebuild.pQGJrT.log
> *** Building scheme "Aspects-tvOS" in Aspects.xcodeproj
> A shell task (/usr/bin/xcrun lipo -create /Users/lawrence/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Aspects/1.4.2-ws1/Build/Intermediates.noindex/ArchiveIntermediates/Aspects-tvOS/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Aspects.framework/Aspects /Users/lawrence/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Aspects/1.4.2-ws1/Build/Products/Release-appletvsimulator/Aspects.framework/Aspects -output /Users/lawrence/code/ably/ably-cocoa/Carthage/Build/tvOS/Aspects.framework/Aspects) failed with exit code 1:
> fatal error: /Applications/Xcode-13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/lawrence/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Aspects/1.4.2-ws1/Build/Intermediates.noindex/ArchiveIntermediates/Aspects-tvOS/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Aspects.framework/Aspects and /Users/lawrence/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Aspects/1.4.2-ws1/Build/Products/Release-appletvsimulator/Aspects.framework/Aspects have the same architectures (arm64) and can't be in the same fat output file

I knew we’ve encountered this issue before and used
Scripts/carthage-with-workaround-for-issue-3019.sh to fix it, so I
assumed something in that script wasn’t working. I saw an "x86_64" there
and assumed it related to the architecture of the platform running the
script, so I changed it to arm64 (i.e. Apple Silicon Mac) and it worked.

Closes #1485.